export const API_DATE_FORMAT = 'yyyy-MM-dd';
export const POLAND_TAX_RATE = 0.19;
export const TO_FIXED_VALUE = 2;
export const CURRENCIES = [
  { value: 'usd', text: 'usd' },
  { value: 'eur', text: 'eur' },
  { value: 'gbp', text: 'gbp' },
  { value: 'thb', text: 'thb' },
  { value: 'aud', text: 'aud' },
  { value: 'hkd', text: 'hkd' },
  { value: 'cad', text: 'cad' },
  { value: 'nzd', text: 'nzd' },
  { value: 'sgd', text: 'sgd' },
  { value: 'huf', text: 'huf' },
  { value: 'chf', text: 'chf' },
  { value: 'uah', text: 'uah' },
  { value: 'jpy', text: 'jpy' },
  { value: 'czk', text: 'czk' },
  { value: 'isk', text: 'isk' },
  { value: 'nok', text: 'nok' },
  { value: 'sek', text: 'sek' },
  { value: 'ron', text: 'ron' },
  { value: 'try', text: 'try' },
  { value: 'ils', text: 'ils' },
  { value: 'clp', text: 'clp' },
  { value: 'php', text: 'php' },
  { value: 'mxn', text: 'mxn' },
  { value: 'zar', text: 'zar' },
  { value: 'brl', text: 'brl' },
  { value: 'myr', text: 'myr' },
  { value: 'idr', text: 'idr' },
  { value: 'inr', text: 'inr' },
  { value: 'krw', text: 'krw' },
  { value: 'cny', text: 'cny' },
  { value: 'xdr', text: 'xdr' },
];
export const MAX_DIVIDEND_DATE = new Date();
